export const SET_SELECTED_RECIPE = 'SET_SELECTED_RECIPE';
export const SET_RECIPE_DETAILS = 'SET_RECIPE_DETAILS';
export const SET_IS_RECIPE_EDITION = 'SET_IS_RECIPE_EDITION';
export const SET_NEW_RECIPE_FIELD = 'SET_NEW_RECIPE_FIELD';
export const ADD_ITEM = 'ADD_PREP_STEP';
export const REMOVE_ITEM = 'REMOVE_PREP_STEP';
